### ISSUE TITLE
Bug when comparing two dates

### ISSUE THREAD

**Issue by fubnuts** [claycephas/csharp-date#2]
Hi,

Not sure if this project is still active but I've been using it and have found a bug. If you write the following code:
```c#
Date date1 = DateTime.Now.ToDate();
System.Threading.Thread.Sleep(1000);
Date date2 = DateTime.Now().ToDate();
```
The date comparison functions will fail:
```c#
Assert.AreEqual(date1, date2);
Assert.IsTrue(date1==date2);
Assert.IsTrue(date1.Equals(date2));
```
This is because there is still a small time portion in the structure in the form of Ticks.

Fortunately there is a way round it - if you change the constructors to no longer Add hours, days etc and change them both to use ".Date":
```c#
public Date(DateTime dateTime)
{
    this._dt = dateTime.Date;
}
```
Apparently using
```c#
dateTime.Subtract(dateTime.TimeOfDay)
```
also works, but I haven't tried that.

Cheers,
Dan.

**Comment by claycephas** [comment]
Great find. Fixed.

**Comment by fubnuts** [comment]
You are most welcome :)
