### ISSUE TITLE
CoreFx lab has a Date implementation

### ISSUE THREAD

**Issue by dennisroche** [claycephas/csharp-date#3]
FYI. 

I just discovered that `System.Time` package from https://github.com/dotnet/corefxlab 

> System.Time. This project augments the date and time APIs in .NET. It adds two new core types: Date and TimeOfDay. It also provides extension methods to enhance the functionality of the existing DateTime, DateTimeOffset and TimeZoneInfo types.

CoreFx is experimental features that the team is trialling, there is no guarantee that they'll be included in the BCL or supported.

**Comment by claycephas** [comment]
Good to know. It's nice to see Microsoft giving some love to some technologies that haven't been updated in a while (things like .Net Core, Windows 10 anniversary update, setting of the path environment variable, ...)
